In [28]:
import numpy as np
import tensorflow as tf
mnist = tf.keras.datasets.mnist

In [29]:
(x_train, y_train),(x_test, y_test) = mnist.load_data()

In [30]:
interpreter = tf.lite.Interpreter(model_path="model_notnorm_nosoft", experimental_preserve_all_tensors=True)
interpreter.allocate_tensors()


f:\FPGA\GUSN\.venv\Lib\site-packages\tensorflow\lite\python\interpreter.py:457: UserWarning:     Warning: tf.lite.Interpreter is deprecated and is scheduled for deletion in
    TF 2.20. Please use the LiteRT interpreter from the ai_edge_litert package.
    See the [migration guide](https://ai.google.dev/edge/litert/migration)
    for details.
    
  warnings.warn(_INTERPRETER_DELETION_WARNING)
f:\FPGA\GUSN\.venv\Lib\site-packages\tensorflow\lite\python\interpreter.py:465: UserWarning: Warning: Enabling `experimental_preserve_all_tensors` with the BUILTIN or AUTO op resolver is intended for debugging purposes only. Be aware that this can significantly increase memory usage by storing all intermediate tensors. If you encounter memory problems or are not actively debugging, consider disabling this option.
  warnings.warn(


In [31]:
input = interpreter.get_input_details()[0]
input

{'name': 'serving_default_flatten_input:0',
 'index': 0,
 'shape': array([ 1, 28, 28]),
 'shape_signature': array([-1, 28, 28]),
 'dtype': numpy.float32,
 'quantization': (0.0, 0),
 'quantization_parameters': {'scales': array([], dtype=float32),
  'zero_points': array([], dtype=int32),
  'quantized_dimension': 0},
 'sparsity_parameters': {}}

In [32]:
input_data = tf.constant(x_test[0], shape=input['shape'], dtype=input['dtype'])
input_data


<tf.Tensor: shape=(1, 28, 28), dtype=float32, numpy=
array([[[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.

In [33]:
interpreter.set_tensor(input['index'], input_data)
interpreter.invoke()

In [34]:
interpreter.get_tensor_details()

[{'name': 'serving_default_flatten_input:0',
  'index': 0,
  'shape': array([ 1, 28, 28]),
  'shape_signature': array([-1, 28, 28]),
  'dtype': numpy.float32,
  'quantization': (0.0, 0),
  'quantization_parameters': {'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32),
   'quantized_dimension': 0},
  'sparsity_parameters': {}},
 {'name': 'arith.constant',
  'index': 1,
  'shape': array([2]),
  'shape_signature': array([2]),
  'dtype': numpy.int32,
  'quantization': (0.0, 0),
  'quantization_parameters': {'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32),
   'quantized_dimension': 0},
  'sparsity_parameters': {}},
 {'name': 'tfl.quantize',
  'index': 2,
  'shape': array([ 1, 28, 28]),
  'shape_signature': array([-1, 28, 28]),
  'dtype': numpy.int8,
  'quantization': (1.0, -128),
  'quantization_parameters': {'scales': array([1.], dtype=float32),
   'zero_points': array([-128]),
   'quantized_dimension': 0},
  'sparsity_parameters': {}}

In [35]:
interpreter.get_tensor(9)

array([[ -90,  -88,  -75,  -75,  -98,  -78, -126,  -66,  -86,  -80]],
      dtype=int8)

In [37]:
np.argmax(interpreter.get_tensor(9))

7

In [43]:
interpreter.get_tensor(7)

array([[-128, -128, -128, -128, -102, -128, -128, -103, -128, -113, -128,
        -128, -128, -128, -128, -128, -128, -128, -128,  -84,  -95, -114,
        -128, -110, -113, -128, -128, -128, -128, -128, -128,  -75,  -57,
        -128, -128, -128, -128, -106, -128,  -88, -128, -103, -128, -120,
        -128, -128, -128, -128, -128, -128, -128, -111,  -86, -128, -128,
        -128, -128, -128, -128, -115,  -97, -122, -128, -128, -117, -128,
         -97, -128, -128, -128, -128, -128,  -99, -128, -128, -128, -101,
        -128, -128,  -24, -128, -113, -128, -128, -128, -128, -128, -128,
        -128, -128, -128, -128, -128, -128, -128, -128, -128, -128, -128,
        -118, -128, -128, -128, -128,  -65, -128, -128, -128, -128, -128,
        -128, -128, -128, -128, -128, -128,  -94, -128, -128,  -95, -128,
        -128, -128,  -86, -128,  -47, -128, -128]], dtype=int8)

In [42]:
interpreter.get_tensor(8)[0]

array([ 55,  57,  20,  54,  51,  28,  37, -54,  16, -12, -23,  28,  37,
         6,  50,   7, -49, -16,  -1,  44,  52,  52,  30,  54,   1,   7,
       -15,  52,  34, -24,  52, -69,  50,  57, -51,  25,  65, -40, -36,
        41,  33,  62,  -7, -76,  47,  44,  62,  21, -94, -64,  29, -37,
        52,  57,  56, -10,  61,  49,  58,  52,  57,  48, -39,  30,  34,
        46,  31,  48,  54,   8,  37, -45,  46,  50,  56,  62,  55,  -4,
        38,  39,  36,  54, -82,  28,  67, -64,  45,  44,  -2,  42,  50,
        17,  18,  39,  46, -21,  29,  50,  19,  45,  54, -60, -31,  -2,
        30,  -5,  34,  11,  52,  48,  55,  56,  59,  51,  34,  11,  -1,
       -16,  42,  41,  55,  61,  45,  43, -77,  45,  23,  73], dtype=int8)

In [44]:
interpreter.get_tensor(4)

array([ 0,  0,  2, -1,  3,  6,  1,  2,  4,  3])

In [ ]:
np.sum((x.astype(np.int32)*y.astype(np.int32) for x,y in zip(interpreter.get_tensor(7)[0], interpreter.get_tensor(8)[0]))).astype(np.int8)


C:\Users\krzys\AppData\Local\Temp\ipykernel_4668\2737353408.py:1: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  np.sum((x.astype(np.int32)*y.astype(np.int32) for x,y in zip(interpreter.get_tensor(7)[0], interpreter.get_tensor(8)[0]))).astype(np.int8)


118

: 